language: java
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq curl
    - sudo curl -L https://github.com/boot-clj/boot-bin/releases/download/2.4.2/boot.sh >/usr/local/bin/boot && sudo chmod 755 /usr/local/bin/boot
script: boot test
