language: java
sudo: false
addons:
    apt:
        packages:
            - curl
before_install:
    - mkdir $PWD/script curl -L https://github.com/boot-clj/boot-bin/releases/download/2.4.2/boot.sh > script/boot && chmod 755 $PWD/script/boot
    - export PATH=$PATH:$PWD/script/
script: boot test


mkdir $PWD/tmp && curl -L https://github.com/n1k0/casperjs/archive/1.0.2.tar.gz > tmp/casper.tar.gz
